### ISSUE TITLE
notify-via-slack fails because of exception in request

### ISSUE THREAD

**Issue by ravimashru** [michael-spengler/cicd#14]
Notifications to Slack are sent successfully, however the PR page shows that the step has failed because of the following exception:

```
error: Uncaught SyntaxError: Unexpected token o in JSON at position 0
    at JSON.parse (<anonymous>)
    at Response.json (deno:op_crates/fetch/26_fetch.js:865:19)
    at async Function.post (https://deno.land/x/request@1.3.0/request.ts:34:27)
    at async notifyViaSlack (https://deno.land/x/cicd@v0.5.4/notify-via-slack.ts:17:5)
```

This looks like it is coming from the https://deno.land/x/request library (because it calls `res.json()` always on the response and maybe the response from Slack is not valid JSON).

@michael-spengler - I can think of 2 options for this:
1. We switch to using the `fetch` API directly in notify-via-slack
2. We make some sort of "fix" for this in the  `Request` library (in which case, I can move this issue to https://github.com/michael-spengler/request).

What do you think?

**Comment by michael-spengler** [comment]
@ravimashru option 2 :)

**Comment by ravimashru** [comment]
@michael-spengler cool! I'll create an issue in that repo to track this. :)
